version: "3"
services:

  app:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - 3000:3000
      - 7000:7000
      - 7002:7002
    volumes:
      - .:/demo-site
    working_dir: /demo-site/app
    command: ["lein", "run", "repl"]


